#!/bin/bash

scala -cp "./guice-lib/guice-2.0.jar:./guice-lib/sitebricks-0.8-SNAPSHOT.jar:./guice-lib/aopalliance.jar:./guice-lib/commons-httpclient-3.1.jar:./guice-lib/commons-logging-1.1.1.jar:./guice-lib/commons-codec-1.3.jar:./guice-lib/google-collect.jar" $*

